{\rtf1\ansi\ansicpg1252\cocoartf2757
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0 ---\
- name: Play1 - WebServer related tasks\
  hosts: webservers\
  become: yes\
  become_user: root\
  tasks:\
    - name: create username apacheadm\
      user:\
        name: apacheadm\
        group: users,admin\
        shell: /bin/bash\
        home: /home/weblogic\
\
    - name: install httpd\
      yum:\
        name: httpd\
        state: installed\
\
- name: Play2 - Application Server related tasks\
  hosts: appservers\
  become: yes\
  become_user: root\
  tasks:\
    - name: Create a username for tomcat\
      user:\
        name: tomcatadm\
        group: users\
        shell: /bin/bash\
        home: /home/tomcat\
\
    - name: create a directory for apache tomcat\
      file:\
        path: /opt/oracle\
        owner: tomcatadm\
        group: users\
        state: directory\
}