{\rtf1\ansi\ansicpg1252\cocoartf2757
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;\red20\green20\blue19;}
{\*\expandedcolortbl;;\cscmyk\c0\c0\c0\c100000;}
\margl1440\margr1440\vieww34060\viewh19040\viewkind0
\pard\tx560\tx1120\tx1680\tx2240\tx2800\tx3360\tx3920\tx4480\tx5040\tx5600\tx6160\tx6720\pardirnatural\partightenfactor0

\f0\fs20 \cf2 ---\
- hosts: backend\
  become: yes\
  tasks:\
    - name: Install python3 and pip\
      yum:\
        name:\
          - python3\
          - python3-pip\
        state: present\
\
    - name: Install Flask\
      pip:\
        name: Flask\
        executable: pip3\
\
    - name: Copy flask app to server\
      copy:\
        src: /path/to/your/Flask/app.py\
        dest: /app/app.py\
\
    - name: Run Flask application\
      shell: nohup python3 /app/app.py > /app/flask.log 2>&1 &\
      args:\
        executable: /bin/bash\
      become_user: root\
\
- hosts: frontend\
  become: yes\
  tasks:\
    - name: Install httpd server\
      yum:\
        name: httpd\
        state: present\
\
    - name: Ensure httpd service is running\
      service:\
        name: httpd\
        state: started\
        enabled: yes\
\
    - name: Copy frontend files to server\
      copy:\
        src: /path/to/your/frontendFiles\
        dest: /var/www/html\
\
    - name: Open port 80 in firewall\
      firewalld:\
        port: 80/tcp\
        permanent: yes\
        state: enabled\
        immediate: yes\
        zone: public\
\'85}